@startuml
scale 350 width
[*] --> CREATED
SCHEDULED_ACTIVITY_CANCEL_COMMAND_CREATED --> SCHEDULED_ACTIVITY_CANCEL_EVENT_RECORDED: ACTIVITY_TASK_CANCEL_REQUESTED
SCHEDULED_ACTIVITY_CANCEL_EVENT_RECORDED --> STARTED_ACTIVITY_CANCEL_EVENT_RECORDED: ACTIVITY_TASK_STARTED
STARTED_ACTIVITY_CANCEL_EVENT_RECORDED --> CANCELED: ACTIVITY_TASK_CANCELED
SCHEDULE_COMMAND_CREATED --> SCHEDULED_EVENT_RECORDED: ACTIVITY_TASK_SCHEDULED
SCHEDULED_EVENT_RECORDED --> SCHEDULED_ACTIVITY_CANCEL_COMMAND_CREATED: CANCEL
STARTED_ACTIVITY_CANCEL_EVENT_RECORDED --> FAILED: ACTIVITY_TASK_FAILED
SCHEDULED_ACTIVITY_CANCEL_COMMAND_CREATED --> STARTED_ACTIVITY_CANCEL_COMMAND_CREATED: ACTIVITY_TASK_STARTED
SCHEDULE_COMMAND_CREATED --> CANCELED: CANCEL
SCHEDULED_ACTIVITY_CANCEL_EVENT_RECORDED --> CANCELED: ACTIVITY_TASK_CANCELED
STARTED_ACTIVITY_CANCEL_COMMAND_CREATED --> COMPLETED: ACTIVITY_TASK_COMPLETED
STARTED_ACTIVITY_CANCEL_EVENT_RECORDED --> COMPLETED: ACTIVITY_TASK_COMPLETED
SCHEDULED_EVENT_RECORDED --> STARTED: ACTIVITY_TASK_STARTED
STARTED --> STARTED_ACTIVITY_CANCEL_COMMAND_CREATED: CANCEL
CREATED --> SCHEDULE_COMMAND_CREATED: SCHEDULE
STARTED --> COMPLETED: ACTIVITY_TASK_COMPLETED
STARTED --> FAILED: ACTIVITY_TASK_FAILED
STARTED_ACTIVITY_CANCEL_COMMAND_CREATED --> FAILED: ACTIVITY_TASK_FAILED
STARTED_ACTIVITY_CANCEL_COMMAND_CREATED --> STARTED_ACTIVITY_CANCEL_EVENT_RECORDED: ACTIVITY_TASK_CANCEL_REQUESTED
COMPLETED --> [*]
FAILED --> [*]
CANCELED --> [*]
@enduml