@startuml
scale 350 width
[*] --> CREATED
SCHEDULED_EVENT_RECORDED --> CANCEL_REQUESTED_SCHEDULED_ACTIVITY: CANCEL
CANCEL_REQUESTED_STARTED_ACTIVITY --> COMPLETED: EVENT_TYPE_ACTIVITY_TASK_COMPLETED
SCHEDULED_EVENT_RECORDED --> STARTED: EVENT_TYPE_ACTIVITY_TASK_STARTED
STARTED --> FAILED: EVENT_TYPE_ACTIVITY_TASK_FAILED
STARTED --> CANCEL_REQUESTED_STARTED_ACTIVITY: CANCEL
CANCEL_REQUESTED_SCHEDULED_ACTIVITY --> FAILED: EVENT_TYPE_ACTIVITY_TASK_FAILED
STARTED --> COMPLETED: EVENT_TYPE_ACTIVITY_TASK_COMPLETED
CANCEL_REQUESTED_SCHEDULED_ACTIVITY --> COMPLETED: EVENT_TYPE_ACTIVITY_TASK_COMPLETED
SCHEDULE_COMMAND_CREATED --> SCHEDULED_EVENT_RECORDED: EVENT_TYPE_ACTIVITY_TASK_SCHEDULED
CANCEL_REQUESTED_SCHEDULED_ACTIVITY --> CANCEL_REQUESTED_STARTED_ACTIVITY: EVENT_TYPE_ACTIVITY_TASK_STARTED
CREATED --> SCHEDULE_COMMAND_CREATED: SCHEDULE
CANCEL_REQUESTED_STARTED_ACTIVITY --> FAILED: EVENT_TYPE_ACTIVITY_TASK_FAILED
CANCEL_REQUESTED_SCHEDULED_ACTIVITY --> CANCELED: EVENT_TYPE_ACTIVITY_TASK_CANCELED
CANCEL_REQUESTED_STARTED_ACTIVITY --> CANCELED: EVENT_TYPE_ACTIVITY_TASK_CANCELED
CREATED --> CANCELED_CREATED_ACTIVITY: CANCEL
COMPLETED --> [*]
FAILED --> [*]
CANCELED --> [*]
CANCELED_CREATED_ACTIVITY --> [*]
@enduml