package io.temporal.internal.csm;

import io.temporal.api.command.v1.CancelWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.Command;
import io.temporal.api.command.v1.CompleteWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.FailWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.RecordMarkerCommandAttributes;
import io.temporal.api.command.v1.RequestCancelExternalWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.ScheduleActivityTaskCommandAttributes;
import io.temporal.api.command.v1.SignalExternalWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.StartChildWorkflowExecutionCommandAttributes;
import io.temporal.api.command.v1.StartTimerCommandAttributes;
import io.temporal.api.command.v1.UpsertWorkflowSearchAttributesCommandAttributes;
import io.temporal.api.history.v1.ActivityTaskCanceledEventAttributes;
import io.temporal.api.history.v1.ActivityTaskCompletedEventAttributes;
import io.temporal.api.history.v1.ActivityTaskFailedEventAttributes;
import io.temporal.api.history.v1.ActivityTaskTimedOutEventAttributes;
import io.temporal.api.history.v1.ChildWorkflowExecutionCanceledEventAttributes;
import io.temporal.api.history.v1.ChildWorkflowExecutionCompletedEventAttributes;
import io.temporal.api.history.v1.ChildWorkflowExecutionFailedEventAttributes;
import io.temporal.api.history.v1.ChildWorkflowExecutionTerminatedEventAttributes;
import io.temporal.api.history.v1.ChildWorkflowExecutionTimedOutEventAttributes;
import io.temporal.api.history.v1.ExternalWorkflowExecutionCancelRequestedEventAttributes;
import io.temporal.api.history.v1.ExternalWorkflowExecutionSignaledEventAttributes;
import io.temporal.api.history.v1.HistoryEvent;
import io.temporal.api.history.v1.RequestCancelExternalWorkflowExecutionFailedEventAttributes;
import io.temporal.api.history.v1.SignalExternalWorkflowExecutionFailedEventAttributes;
import io.temporal.api.history.v1.StartChildWorkflowExecutionFailedEventAttributes;
import io.temporal.api.history.v1.TimerCanceledEventAttributes;
import io.temporal.api.history.v1.TimerFiredEventAttributes;
import io.temporal.workflow.Functions;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public final class CommandsManager {

  private Functions.Proc1<NewCommand> sink;

  private final Map<Long, CommandsBase> commands = new HashMap<>();

  /** Commands generated by the currently processed workflow task. */
  private final List<NewCommand> newCommands = new ArrayList<>();

  public CommandsManager() {
    sink = (command) -> newCommands.add(command);
  }

  public List<Command> takeCommands(long firstCommandEventId) {
    List<Command> result = new ArrayList<>(newCommands.size());
    for (NewCommand newCommand : newCommands) {
      Optional<Command> command = newCommand.getCommand();
      if (command.isPresent()) {
        result.add(command.get());
        newCommand.setInitialCommandEventId(firstCommandEventId++);
        commands.put(firstCommandEventId, newCommand.getCommands());
        firstCommandEventId++;
      }
    }
    return result;
  }

  public void newActivity(
      ScheduleActivityTaskCommandAttributes attributes,
      Functions.Proc4<
              ActivityTaskCompletedEventAttributes,
              ActivityTaskFailedEventAttributes,
              ActivityTaskTimedOutEventAttributes,
              ActivityTaskCanceledEventAttributes>
          completionCallback) {
    ActivityCommands.newInstance(attributes, completionCallback, sink);
  }

  /**
   * Creates a new timer state machine
   *
   * @param attributes timer command attributes
   * @param completionCallback invoked when timer fires or reports cancellation
   * @return cancellation callback that should be invoked to initiate timer cancellation
   */
  public Functions.Proc newTimer(
      StartTimerCommandAttributes attributes,
      Functions.Proc2<TimerFiredEventAttributes, TimerCanceledEventAttributes> completionCallback) {
    TimerCommands timer = TimerCommands.newInstance(attributes, completionCallback, sink);
    return () -> timer.cancel();
  }

  /**
   * Creates a new child state machine
   *
   * @param attributes child workflow start command attributes
   * @param completionCallback invoked when child reports completion or failure
   * @return cancellation callback that should be invoked to cancel the child
   */
  public Functions.Proc newChildWorkflow(
      StartChildWorkflowExecutionCommandAttributes attributes,
      Functions.Proc6<
              StartChildWorkflowExecutionFailedEventAttributes,
              ChildWorkflowExecutionCompletedEventAttributes,
              ChildWorkflowExecutionFailedEventAttributes,
              ChildWorkflowExecutionTimedOutEventAttributes,
              ChildWorkflowExecutionCanceledEventAttributes,
              ChildWorkflowExecutionTerminatedEventAttributes>
          completionCallback) {
    ChildWorkflowCommands child =
        ChildWorkflowCommands.newInstance(attributes, completionCallback, sink);
    return () -> child.cancel();
  }

  public void newSignalExternal(
      SignalExternalWorkflowExecutionCommandAttributes attributes,
      Functions.Proc2<
              ExternalWorkflowExecutionSignaledEventAttributes,
              SignalExternalWorkflowExecutionFailedEventAttributes>
          completionCallback) {
    SignalExternalCommands.newInstance(attributes, completionCallback, sink);
  }

  public void newCancelExternal(
      RequestCancelExternalWorkflowExecutionCommandAttributes attributes,
      Functions.Proc2<
              ExternalWorkflowExecutionCancelRequestedEventAttributes,
              RequestCancelExternalWorkflowExecutionFailedEventAttributes>
          completionCallback) {
    CancelExternalCommands.newInstance(attributes, completionCallback, sink);
  }

  public void newUpsertSearchAttributes(
      UpsertWorkflowSearchAttributesCommandAttributes attributes) {
    UpsertSearchAttributesCommands.newInstance(attributes, sink);
  }

  public void newMarker(RecordMarkerCommandAttributes attributes) {
    MarkerCommands.newInstance(attributes, sink);
  }

  public void newCompleteWorkflow(CompleteWorkflowExecutionCommandAttributes attributes) {
    CompleteWorkflowCommands.newInstance(attributes, sink);
  }

  public void newFailWorkflow(FailWorkflowExecutionCommandAttributes attributes) {
    FailWorkflowCommands.newInstance(attributes, sink);
  }

  public void newCancelWorkflow(CancelWorkflowExecutionCommandAttributes attributes) {
    CancelWorkflowCommands.newInstance(attributes, sink);
  }

  private long getInitialCommandEventId(HistoryEvent event) {
    switch (event.getEventType()) {
      case EVENT_TYPE_ACTIVITY_TASK_STARTED:
        return event.getActivityTaskStartedEventAttributes().getScheduledEventId();
      case EVENT_TYPE_ACTIVITY_TASK_COMPLETED:
        return event.getActivityTaskCompletedEventAttributes().getScheduledEventId();
      case EVENT_TYPE_ACTIVITY_TASK_FAILED:
        return event.getActivityTaskFailedEventAttributes().getScheduledEventId();
      case EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT:
        return event.getActivityTaskTimedOutEventAttributes().getScheduledEventId();
      case EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED:
        return event.getActivityTaskCancelRequestedEventAttributes().getScheduledEventId();
      case EVENT_TYPE_REQUEST_CANCEL_ACTIVITY_TASK_FAILED:
        throw new IllegalArgumentException("Unexpected event type: " + event.getEventType());
      case EVENT_TYPE_ACTIVITY_TASK_CANCELED:
        break;
      case EVENT_TYPE_TIMER_STARTED:
        break;
      case EVENT_TYPE_TIMER_FIRED:
        break;
      case EVENT_TYPE_CANCEL_TIMER_FAILED:
        break;
      case EVENT_TYPE_TIMER_CANCELED:
        break;
      case EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED:
        break;
      case EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED:
        break;
      case EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED:
        break;
      case EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED:
        break;
      case EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_CANCEL_REQUESTED:
        break;
      case EVENT_TYPE_MARKER_RECORDED:
        break;
      case EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED:
        break;
      case EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED:
        break;
      case EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW:
        break;
      case EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED:
        break;
      case EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_FAILED:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TIMED_OUT:
        break;
      case EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TERMINATED:
        break;
      case EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED:
        break;
      case EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED:
        break;
      case EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_SIGNALED:
        break;
      case EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES:
        break;
      case UNRECOGNIZED:
        break;
    }
  }
}
